@ASB_Test_HostAddress = https://localhost:7180/


POST {{ASB_Test_HostAddress}}QueueOne/SendMessage?message=testmessage
Accept: application/json
###

GET {{ASB_Test_HostAddress}}QueueOne/GetMessage
Accept: application/json
###